default: &DEFAULT
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0
  host: localhost
  username: <%= `whoami`.strip.inspect %>
  port: <%= ENV['DB_PORT'] || 5432 %>

development:
  <<: *DEFAULT
  database: myspree_development

production:
  <<: *DEFAULT
  # database: myspree_development
  pool: 10
  database: <%= ENV["DATABASE"] || 'myspree_development' %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV["DATAUSER"] %>
  password: <%= ENV["DATAPASSWD"] %>

test: &TEST
  <<: *DEFAULT
  database: myspree_test
